<?php
/**
 * Catalog content as it was hardcoded on the website before Step 3.5
 * (homepage, services.php, header menu and the nine category pages).
 * Read by database/seed_catalog_from_website.php. Images are paths
 * relative to the website root and are copied into uploads/admin/.
 */
return [
    'categories' => [
        [
            'slug' => 'ac-service',
            'name' => 'AC Service',
            'match' => ['AC Repair & Service'],
            'page_title' => 'AC Service & Repair',
            'description' => 'Professional AC servicing, repair, installation, gas refill and maintenance at your doorstep.',
            'tagline' => 'Service & repair',
            'icon' => 'fa-solid fa-snowflake',
            'label' => 'COOLING',
            'highlights' => ['AC Repair', 'Foam Jet Service', 'Installation'],
            'image' => 'images/ac-service.jfif',
            'cover_image' => 'images/professional-ac-service.png',
            'sort' => 1,
            'services' => [
                [
                    'slug' => 'ac-foam-jet',
                    'name' => 'Foam-Jet AC Service',
                    'match' => ['Foam-jet service (2 ACs)'],
                    'tag' => 'POPULAR PACKAGE',
                    'description' => 'Professional deep cleaning for improved cooling efficiency and better AC performance.',
                    'highlights' => ['Deep AC Cleaning', 'Filter Cleaning', 'Cooling Inspection'],
                    'price' => 1400,
                    'image' => 'images/foam-jet-ac-service.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'ac-gas-refill',
                    'name' => 'AC Gas Leak Fix & Refill',
                    'match' => ['Gas Refill'],
                    'tag' => 'AC REPAIR',
                    'description' => 'Professional inspection of refrigerant leaks followed by gas refill for optimal cooling.',
                    'highlights' => ['Gas Leakage Check', 'Cooling Inspection', 'Refrigerant Refill'],
                    'price' => 2899,
                    'image' => 'images/ac-gas-leak-fix.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'ac-installation',
                    'name' => 'AC Installation',
                    'match' => [],
                    'tag' => 'INSTALLATION',
                    'description' => 'Professional AC installation with secure mounting, electrical connection and testing.',
                    'highlights' => ['Secure Mounting', 'Electrical Connection', 'Performance Testing'],
                    'price' => 1499,
                    'image' => 'images/ac-installation-service.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'ac-uninstallation',
                    'name' => 'AC Uninstallation',
                    'match' => [],
                    'tag' => 'REMOVAL SERVICE',
                    'description' => 'Safe and professional AC removal with proper handling of electrical and drainage connections.',
                    'highlights' => ['Safe AC Removal', 'Pipe Disconnection', 'Component Handling'],
                    'price' => 1299,
                    'image' => 'images/ac-uninstallation.png',
                    'sort' => 4,
                ],
            ],
        ],
        [
            'slug' => 'refrigerator-repair',
            'name' => 'Refrigerator Repair',
            'match' => ['Refrigerator Repair & Service'],
            'page_title' => 'Refrigerator Repair Services',
            'description' => 'Professional refrigerator inspection, repair, cooling diagnosis, gas refill and maintenance at your doorstep.',
            'tagline' => 'Expert appliance repair',
            'icon' => 'fa-solid fa-temperature-low',
            'label' => 'APPLIANCE',
            'highlights' => ['Cooling Repair', 'Gas Refilling', 'Leakage Repair'],
            'image' => 'images/refrigerator-service.png',
            'cover_image' => 'images/refrigerator-services.png',
            'sort' => 2,
            'services' => [
                [
                    'slug' => 'refrigerator-not-cooling',
                    'name' => 'Refrigerator Not Cooling – Inspection',
                    'match' => ['Refrigerator Not Cooling ? Inspection'],
                    'tag' => 'INSPECTION',
                    'description' => 'Expert diagnosis and inspection for refrigerators experiencing insufficient or uneven cooling.',
                    'highlights' => ['Cooling System Inspection', 'Component Diagnosis', 'Performance Check'],
                    'price' => 349,
                    'image' => 'images/refrigerator-not-cooling.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'refrigerator-water-leakage',
                    'name' => 'Refrigerator Water Leakage',
                    'match' => ['Refrigerator Water Leakage ? Inspection'],
                    'tag' => 'LEAKAGE REPAIR',
                    'description' => 'Diagnose and clear blocked drains, inspect or replace seals and test for leak-free operation.',
                    'highlights' => ['Leakage Diagnosis', 'Drain Inspection', 'Seal Inspection'],
                    'price' => 399,
                    'image' => 'images/refrigerator-water-leakage.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'refrigerator-ice-maker-repair',
                    'name' => 'Refrigerator Ice Maker Repair',
                    'match' => ['Refrigerator Ice Maker Repair - Inspection'],
                    'tag' => 'ICE MAKER SERVICE',
                    'description' => 'Ice maker inspection, diagnosis and repair to restore proper ice-making functionality.',
                    'highlights' => ['Ice Maker Inspection', 'Component Diagnosis', 'Functionality Testing'],
                    'price' => 999,
                    'image' => 'images/refrigerator-ice-maker-repair.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'refrigerator-defrosting',
                    'name' => 'Refrigerator Defrosting Issues',
                    'match' => ['Refrigerator Defrosting Issues - Inspection'],
                    'tag' => 'DEFROST REPAIR',
                    'description' => 'Defrost system check and diagnosis to restore proper cooling and prevent excessive ice build-up.',
                    'highlights' => ['Defrost System Check', 'Frost Diagnosis', 'Cooling Performance Test'],
                    'price' => 999,
                    'image' => 'images/refrigerator-defrosting-issues.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'refrigerator-gas-refilling',
                    'name' => 'Refrigerator Gas Refilling',
                    'match' => ['Refrigerator Gas Refilling Inspection'],
                    'tag' => 'GAS REFILL',
                    'description' => 'Gas level check, leak inspection and refrigerant refill to restore optimal refrigerator cooling.',
                    'highlights' => ['Gas Level Check', 'Leak Inspection', 'Refrigerant Refilling'],
                    'price' => 1499,
                    'image' => 'images/refrigerator-gas-refilling.png',
                    'sort' => 5,
                ],
                [
                    'slug' => 'single-door-refrigerator',
                    'name' => 'Single Door Refrigerator',
                    'match' => ['Single Door Refrigerator Repair'],
                    'tag' => 'SINGLE DOOR',
                    'description' => 'Inspection, diagnosis and repair service for single-door refrigerators.',
                    'highlights' => ['Refrigerator Inspection', 'Fault Diagnosis', 'Repair & Testing'],
                    'price' => 599,
                    'image' => 'images/single-door-refrigerator.png',
                    'sort' => 6,
                ],
                [
                    'slug' => 'double-door-refrigerator-inverter',
                    'name' => 'Double Door Refrigerator (Inverter)',
                    'match' => ['Double Door Refrigerator Repair (Inverter)'],
                    'tag' => 'DOUBLE DOOR',
                    'description' => 'Professional inspection and repair service for inverter double-door refrigerators.',
                    'highlights' => ['Inverter System Check', 'Sensor Diagnosis', 'Repair & Testing'],
                    'price' => 799,
                    'image' => 'images/double-door-refrigerator-inverter.png',
                    'sort' => 7,
                ],
                [
                    'slug' => 'double-door-refrigerator-non-inverter',
                    'name' => 'Double Door Refrigerator (Non-Inverter)',
                    'match' => ['Double Door Refrigerator Repair (Non-Inverter)'],
                    'tag' => 'DOUBLE DOOR',
                    'description' => 'Inspection and repair service designed for non-inverter double-door refrigerators.',
                    'highlights' => ['Cooling System Check', 'Compressor Inspection', 'Repair & Testing'],
                    'price' => 799,
                    'image' => 'images/double-door-refrigerator-non-inverter.png',
                    'sort' => 8,
                ],
                [
                    'slug' => 'side-by-side-refrigerator',
                    'name' => 'Side by Side Door Refrigerator',
                    'match' => ['Side by Side Refrigerator Repair'],
                    'tag' => 'SIDE-BY-SIDE',
                    'description' => 'Inspection, diagnosis and repair service for side-by-side refrigerator systems.',
                    'highlights' => ['Complete Inspection', 'Sensor & Compressor Check', 'Repair & Performance Test'],
                    'price' => 999,
                    'image' => 'images/side-by-side-refrigerator.png',
                    'sort' => 9,
                ],
            ],
        ],
        [
            'slug' => 'home-cleaning',
            'name' => 'Home Cleaning',
            'match' => ['Home Cleaning'],
            'page_title' => 'Home Cleaning Services',
            'description' => 'Professional full-home and bathroom cleaning services for furnished and unfurnished homes at your doorstep.',
            'tagline' => 'Deep cleaning services',
            'icon' => 'fa-solid fa-broom',
            'label' => 'CLEANING',
            'highlights' => ['Deep Cleaning', 'Bathroom Cleaning', 'Full Home Cleaning'],
            'image' => 'images/home-cleaning-service.png',
            'cover_image' => 'images/home-cleaning-services.png',
            'sort' => 3,
            'services' => [
                [
                    'slug' => 'basic-full-home-cleaning',
                    'name' => 'Basic Full Home Cleaning',
                    'match' => [],
                    'tag' => 'FULL HOME CLEANING',
                    'description' => 'Regular upkeep and general cleaning including dusting, vacuuming, mopping and surface cleaning in all rooms.',
                    'highlights' => ['Complete Dusting', 'Vacuuming & Mopping', 'Surface Cleaning'],
                    'price' => 2799,
                    'image' => 'images/basic-full-home-cleaning.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'deep-full-home-cleaning',
                    'name' => 'Deep Full Home Cleaning',
                    'match' => [],
                    'tag' => 'DEEP CLEANING',
                    'description' => 'Thorough home cleaning with deep vacuuming, upholstery care, machine scrubbing and appliance interior cleaning.',
                    'highlights' => ['Deep Vacuuming', 'Machine Scrubbing', 'Upholstery & Appliance Care'],
                    'price' => 3499,
                    'image' => 'images/deep-full-home-cleaning.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'unfurnished-apartment-basic-cleaning',
                    'name' => 'Unfurnished Apartment Basic Full Home Cleaning',
                    'match' => [],
                    'tag' => 'UNFURNISHED HOME',
                    'description' => 'Regular upkeep of unfurnished spaces including sweeping, mopping, dusting and surface cleaning.',
                    'highlights' => ['Floor Sweeping', 'Mopping & Dusting', 'Surface Cleaning'],
                    'price' => 1999,
                    'image' => 'images/unfurnished-apartment-cleaning.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'furnished-independent-basic-cleaning',
                    'name' => 'Furnished Independent Basic Full Home Cleaning',
                    'match' => [],
                    'tag' => 'FURNISHED HOME',
                    'description' => 'Routine upkeep with light dusting, vacuuming, mopping, surface cleaning and light manual scrubbing.',
                    'highlights' => ['Light Dusting', 'Vacuuming & Mopping', 'Light Manual Scrubbing'],
                    'price' => 2499,
                    'image' => 'images/furnished-independent-home-cleaning.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'bathroom-cleaning',
                    'name' => 'Bathroom Cleaning',
                    'match' => [],
                    'tag' => 'BATHROOM SERVICE',
                    'description' => 'Wet cleaning of bathroom fixtures, stain removal on fittings, deep tile cleaning and surface sanitization.',
                    'highlights' => ['Fixture Cleaning', 'Tile Deep Cleaning', 'Surface Sanitization'],
                    'price' => 899,
                    'image' => 'images/bathroom-cleaning.png',
                    'sort' => 5,
                ],
            ],
        ],
        [
            'slug' => 'salon',
            'name' => 'Salon',
            'match' => ['Salon'],
            'page_title' => 'Facial & Beauty Services',
            'description' => 'Professional facial and beauty care services designed to cleanse, refresh, brighten and rejuvenate your skin at your doorstep.',
            'tagline' => 'Beauty at your doorstep',
            'icon' => 'fa-solid fa-scissors',
            'label' => 'PERSONAL CARE',
            'highlights' => ['Facial Services', 'Skin Care', 'Threading'],
            'image' => 'images/salon-service.png',
            'cover_image' => 'images/facial-beauty-service.png',
            'sort' => 4,
            'services' => [
                [
                    'slug' => 'beauty-brightening-facial',
                    'name' => 'Brightening Facial',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'The Brightening Facial nourishes, rejuvenates and brightens the skin while helping reduce dark spots.',
                    'highlights' => ['Cleanse & Vitamin-C Peel', 'Extract & Massage', 'Brightening Pack & Serum'],
                    'price' => 259,
                    'image' => 'images/brightening-facial.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'beauty-anti-tanning-facial',
                    'name' => 'Anti-Tanning Facial',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'The Anti-Tanning Facial helps lighten tanned skin, brighten dull patches and promote an even-looking skin tone.',
                    'highlights' => ['Cleanse & Scrub', 'Massage Gel & Cream', 'De-Tan Face Pack'],
                    'price' => 259,
                    'image' => 'images/anti-tanning-facial.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'beauty-o2-stay-youthful',
                    'name' => 'O2 Stay Youthful',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'The O2 Stay Youthful treatment helps boost hydration, promote an even skin tone and support a luminous glow.',
                    'highlights' => ['Cleanse & Exfoliate', 'Relaxing Massage', 'Hydrating Face Mask'],
                    'price' => 259,
                    'image' => 'images/o2-stay-youthful.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'beauty-gold-facial',
                    'name' => 'Gold Facial',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Experience a luxurious Gold Facial designed to improve skin radiance while helping reduce the appearance of wrinkles and fine lines.',
                    'highlights' => ['Cleanse & Lactic Peel', 'Massage & Gold Peel-Off Mask', 'Serum & Sunscreen'],
                    'price' => 279,
                    'image' => 'images/gold-facial.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'beauty-instant-glow-facial',
                    'name' => 'Instant Glow Facial',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'The Instant Glow Facial is designed to illuminate the skin and reveal a fresh, vibrant-looking complexion.',
                    'highlights' => ['Cleanse & Exfoliate', 'Extract & Mask', 'SPF & Relaxing Massage'],
                    'price' => 249,
                    'image' => 'images/instant-glow-facial.png',
                    'sort' => 5,
                ],
                [
                    'slug' => 'beauty-threading',
                    'name' => 'Threading',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Professional threading service with gentle skin preparation and soothing post-service care.',
                    'highlights' => ['Skin Cleansing', 'Gentle Threading', 'Post-Service Massage'],
                    'price' => 199,
                    'image' => 'images/threading-service.png',
                    'sort' => 6,
                ],
            ],
        ],
        [
            'slug' => 'pest-control',
            'name' => 'Pest Control',
            'match' => ['Pest Control'],
            'page_title' => 'Pest Control Services',
            'description' => 'Professional pest control solutions for apartments, independent houses, kitchens, bathrooms, offices and shops.',
            'tagline' => 'Safe pest solutions',
            'icon' => 'fa-solid fa-bug',
            'label' => 'HOME PROTECTION',
            'highlights' => ['Cockroach Control', 'Bed Bug Control', 'Home Pest Control'],
            'image' => 'images/past-control-service.png',
            'cover_image' => 'images/pest-control-service.png',
            'sort' => 5,
            'services' => [
                [
                    'slug' => 'pest-kitchen-bathroom',
                    'name' => 'Kitchen & Bathroom Pest Control',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Pest control treatment for kitchens and bathrooms with focus on hidden areas, cracks, drains and common pest-prone spaces.',
                    'highlights' => ['Complete Inspection', 'Eco-Friendly Treatment', 'Crack & Drain Coverage'],
                    'price' => 500,
                    'image' => 'images/kitchen-bathroom-pest-control.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'pest-apartment-utensil',
                    'name' => 'Apartment Pest Control - Includes Utensil Removal',
                    'match' => ['Apartment Pest Control (Includes Utensil Removal)'],
                    'tag' => 'PACKAGE',
                    'description' => 'Thorough inspection, utensil removal and professional pest treatment designed to access hidden areas throughout your apartment.',
                    'highlights' => ['Thorough Inspection', 'Utensil Removal', 'Crack & Drain Coverage'],
                    'price' => 1000,
                    'image' => 'images/apartment-pest-control-utensil-removal.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'pest-apartment',
                    'name' => 'Apartment Pest Control - Excludes Utensil Removal',
                    'match' => ['Apartment Pest Control (Excludes Utensil Removal)'],
                    'tag' => 'PACKAGE',
                    'description' => 'An affordable pest control service for apartments where utensil removal can be managed by the homeowner.',
                    'highlights' => ['Complete Inspection', 'Safe Pest Treatment', 'Perimeter Protection'],
                    'price' => 750,
                    'image' => 'images/apartment-pest-control.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'pest-independent-house',
                    'name' => 'Independent House Pest Control',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Premium pest control service for bungalows and independent houses with treatment of hidden and hard-to-reach areas.',
                    'highlights' => ['Internal Inspection', 'Crack & Drain Treatment', 'Perimeter Safety'],
                    'price' => 1500,
                    'image' => 'images/independent-house-pest-control.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'pest-cockroach-control',
                    'name' => 'Cockroach Control Treatment',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Professional cockroach control treatment focusing on cracks, drains, hidden spaces and areas commonly affected by cockroach activity.',
                    'highlights' => ['Inspection', 'Gel Bait / Spray Treatment', 'Crack & Drain Coverage'],
                    'price' => 500,
                    'image' => 'images/cockroach-control-treatment.png',
                    'sort' => 5,
                ],
                [
                    'slug' => 'pest-bed-bug-control',
                    'name' => 'Bed Bug Control',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Professional bed bug treatment covering beds, mattresses, furniture and common hiding areas around your room.',
                    'highlights' => ['Complete Inspection', 'Mattress & Furniture Care', 'Crack Coverage'],
                    'price' => 350,
                    'image' => 'images/bed-bug-control.png',
                    'sort' => 6,
                ],
                [
                    'slug' => 'pest-commercial',
                    'name' => 'Commercial Office/Shop Pest Control',
                    'match' => ['Office/Shop Pest Control'],
                    'tag' => 'PACKAGE',
                    'description' => 'Comprehensive inspections and professional treatments designed to provide effective pest control for offices, shops and business spaces.',
                    'highlights' => ['Comprehensive Inspection', 'Tailored Pest Treatment', 'Prevention Guidance'],
                    'price' => 1500,
                    'image' => 'images/commercial-pest-control.png',
                    'sort' => 7,
                ],
            ],
        ],
        [
            'slug' => 'washing-machine-repair',
            'name' => 'Washing Machine Repair',
            'match' => ['Washing Machine Repair & Services'],
            'page_title' => 'Washing Machine Service & Repair',
            'description' => 'Professional washing machine inspection, repair, installation and maintenance at your doorstep.',
            'tagline' => 'Service & maintenance',
            'icon' => 'fa-solid fa-soap',
            'label' => 'APPLIANCE',
            'highlights' => ['Top Load', 'Front Load', 'Installation'],
            'image' => 'images/washing-machine-repair-service.png',
            'cover_image' => 'images/washing-machine-service.png',
            'sort' => 6,
            'services' => [
                [
                    'slug' => 'washing-top-load-inspection',
                    'name' => 'Top Load Fully Automatic - Inspection',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Inspection & diagnosis, repair quote, spare part sourcing help and post-inspection area cleaning.',
                    'highlights' => ['Complete Machine Inspection', 'Diagnosis & Repair Quote', 'Spare Part Sourcing Assistance'],
                    'price' => 449,
                    'image' => 'images/top-load-washing-machine.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'washing-front-load-inspection',
                    'name' => 'Front Load Fully Automatic - Inspection',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Inspection & diagnosis, repair quote, spare part sourcing help and post-inspection area cleaning.',
                    'highlights' => ['Complete Machine Inspection', 'Diagnosis & Repair Quote', 'Spare Part Sourcing Assistance'],
                    'price' => 449,
                    'image' => 'images/front-load-washing-machine.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'washing-semi-automatic-inspection',
                    'name' => 'Semi-Automatic - Inspection',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Inspection & diagnosis, repair quote, spare part sourcing help and post-inspection area cleaning.',
                    'highlights' => ['Machine Inspection', 'Diagnosis & Repair Quote', 'Post-Inspection Area Cleaning'],
                    'price' => 449,
                    'image' => 'images/semi-automatic-washing-machine.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'washing-machine-installation',
                    'name' => 'Washing Machine Installation',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Unpacking, placement, connections, leveling, test cycle and demo. All models installed with care.',
                    'highlights' => ['Machine Placement & Leveling', 'Water & Drain Connections', 'Test Cycle & Demonstration'],
                    'price' => 499,
                    'image' => 'images/washing-machine-installation.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'washing-machine-uninstallation',
                    'name' => 'Washing Machine Uninstallation',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Safe washing machine removal including disconnection, removal and cleaning up the service area.',
                    'highlights' => ['Safe Machine Disconnection', 'Water & Drain Pipe Removal', 'Service Area Cleaning'],
                    'price' => 499,
                    'image' => 'images/washing-machine-uninstallation.png',
                    'sort' => 5,
                ],
            ],
        ],
        [
            'slug' => 'chimney-repair',
            'name' => 'Chimney Repair',
            'match' => ['Chimney Repair'],
            'page_title' => 'Chimney Service & Repair',
            'description' => 'Professional chimney inspection, cleaning, repair, installation and maintenance at your doorstep.',
            'tagline' => 'Cleaning & repair',
            'icon' => 'fa-solid fa-kitchen-set',
            'label' => 'KITCHEN',
            'highlights' => ['Chimney Cleaning', 'Motor Repair', 'Installation'],
            'image' => 'images/chimney-repair-service.png',
            'cover_image' => 'images/chimney-services.png',
            'sort' => 7,
            'services' => [
                [
                    'slug' => 'chimney-suction-power',
                    'name' => 'Chimney Suction Power Issues',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Complete Chimney check-up to identify suction power issues before repair.',
                    'highlights' => ['Suction Power Inspection', 'Blockage Identification', 'Performance Diagnosis'],
                    'price' => 499,
                    'image' => 'images/chimney-suction-power-issues.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'chimney-fan-blower',
                    'name' => 'Chimney Fan/Blower Repair',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Complete Chimney check-up to identify fan blower issues before repair.',
                    'highlights' => ['Fan Inspection', 'Blower Diagnosis', 'Smoke Extraction Check'],
                    'price' => 599,
                    'image' => 'images/chimney-fan-blower-repair.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'chimney-control-panel',
                    'name' => 'Chimney Button/Control Panel Repair',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Complete Chimney check-up to identify control panel issues before repair.',
                    'highlights' => ['Button Inspection', 'Control Panel Diagnosis', 'Function Testing'],
                    'price' => 499,
                    'image' => 'images/chimney-control-panel-repair.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'chimney-duct-repair',
                    'name' => 'Chimney Duct Repair/Replacement',
                    'match' => ['Chimney Duct Repair'],
                    'tag' => 'PACKAGE',
                    'description' => 'Complete Chimney check-up to identify duct issues before repair/replacement.',
                    'highlights' => ['Ductwork Inspection', 'Smoke Flow Check', 'Repair Assessment'],
                    'price' => 549,
                    'image' => 'images/chimney-duct-repair.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'chimney-cleaning',
                    'name' => 'Chimney Cleaning Service',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Cleans chimney components and ducts; excludes filter replacement, repairs and electrical work.',
                    'highlights' => ['Grease Cleaning', 'Soot Removal', 'Chimney Maintenance'],
                    'price' => 399,
                    'image' => 'images/chimney-cleaning-service.png',
                    'sort' => 5,
                ],
                [
                    'slug' => 'chimney-motor-repair',
                    'name' => 'Chimney Motor Repair',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Complete Chimney check-up to identify motor issues before repair.',
                    'highlights' => ['Motor Inspection', 'Suction Performance Check', 'Repair Assessment'],
                    'price' => 499,
                    'image' => 'images/chimney-motor-repair.png',
                    'sort' => 6,
                ],
                [
                    'slug' => 'chimney-installation',
                    'name' => 'Chimney Installation Service',
                    'match' => ['Chimney Installation'],
                    'tag' => 'PACKAGE',
                    'description' => 'Installs chimney unit, sets up ducting, tests operation and checks electrical safety.',
                    'highlights' => ['Chimney Installation', 'Duct Setup', 'Operation & Safety Testing'],
                    'price' => 499,
                    'image' => 'images/chimney-installation-service.png',
                    'sort' => 7,
                ],
                [
                    'slug' => 'chimney-uninstallation',
                    'name' => 'Chimney Uninstallation Service',
                    'match' => ['Chimney Uninstallation'],
                    'tag' => 'PACKAGE',
                    'description' => 'Removes chimney unit safely, disconnects components, seals ducts, cleans the area and checks for damage.',
                    'highlights' => ['Safe Chimney Removal', 'Component Disconnection', 'Area Cleaning'],
                    'price' => 499,
                    'image' => 'images/chimney-uninstallation-service.png',
                    'sort' => 8,
                ],
            ],
        ],
        [
            'slug' => 'water-purifier',
            'name' => 'Water Purifier',
            'match' => ['Water Purifier Service'],
            'page_title' => 'Water Purifier Service & Repair',
            'description' => 'Professional water purifier servicing, repair, installation and maintenance at your doorstep.',
            'tagline' => 'RO service & repair',
            'icon' => 'fa-solid fa-droplet',
            'label' => 'WATER CARE',
            'highlights' => ['Filter Replacement', 'Pump Repair', 'Installation'],
            'image' => 'images/water-purifier-service.png',
            'cover_image' => 'images/water-purifier-services.png',
            'sort' => 8,
            'services' => [
                [
                    'slug' => 'water-purifier-service',
                    'name' => 'Water Purifier Service',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Inspect purifier, clean filters and RO membrane, replace if needed, check TDS, test functions, inspect for leaks, and verify UV/pump.',
                    'highlights' => ['Complete Purifier Inspection', 'Filter & RO Membrane Check', 'TDS & Function Testing'],
                    'price' => 399,
                    'image' => 'images/water-purifier-service.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'water-purifier-not-dispensing',
                    'name' => 'Water Purifier Not Dispensing Water',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Diagnose flow issues, clean or replace filters, and repair or replace faulty components affecting water flow.',
                    'highlights' => ['Water Flow Diagnosis', 'Filter Inspection', 'Component Check'],
                    'price' => 399,
                    'image' => 'images/water-purifier-not-dispensing-water.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'water-purifier-low-pressure',
                    'name' => 'Water Purifier Low Water Pressure',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Diagnose pressure issues, clean or replace filters, and test for proper water pressure and flow.',
                    'highlights' => ['Pressure Diagnosis', 'Filter Inspection', 'Water Flow Testing'],
                    'price' => 399,
                    'image' => 'images/water-purifier-low-pressure.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'water-purifier-pump-repair',
                    'name' => 'Water Purifier Pump Repair/Replacement',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Diagnose pump issues, repair or replace malfunctioning pump, and test for proper pressure and water flow.',
                    'highlights' => ['Pump Diagnosis', 'Pump Repair Assessment', 'Pressure & Flow Testing'],
                    'price' => 399,
                    'image' => 'images/water-purifier-pump-repair.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'water-purifier-uv-lamp',
                    'name' => 'Water Purifier UV Lamp Replacement',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Diagnose taste or odor issues, clean or replace filters and test the purifier for improved water quality.',
                    'highlights' => ['UV Lamp Inspection', 'Water Quality Check', 'Purifier Function Testing'],
                    'price' => 399,
                    'image' => 'images/water-purifier-uv-lamp-replacement.png',
                    'sort' => 5,
                ],
                [
                    'slug' => 'water-purifier-filter-replacement',
                    'name' => 'Water Purifier Filter Replacement',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Remove old filters, install new ones, and test the purifier for optimal purification performance.',
                    'highlights' => ['Old Filter Removal', 'New Filter Installation', 'Purification Testing'],
                    'price' => 599,
                    'image' => 'images/water-purifier-filter-replacement.png',
                    'sort' => 6,
                ],
                [
                    'slug' => 'water-purifier-installation',
                    'name' => 'Water Purifier Installation',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Mount and install water purifier, connect to supply lines, test operation, check for leaks and secure all connections.',
                    'highlights' => ['Purifier Mounting', 'Water Supply Connection', 'Leak & Operation Testing'],
                    'price' => 349,
                    'image' => 'images/water-purifier-installation.png',
                    'sort' => 7,
                ],
                [
                    'slug' => 'water-purifier-uninstallation',
                    'name' => 'Water Purifier Uninstallation',
                    'match' => [],
                    'tag' => 'PACKAGE',
                    'description' => 'Safely disconnect water purifier, unmount unit, seal connections to prevent leaks and clean up the work area.',
                    'highlights' => ['Safe Disconnection', 'Purifier Unmounting', 'Connection Sealing'],
                    'price' => 349,
                    'image' => 'images/water-purifier-uninstallation.png',
                    'sort' => 8,
                ],
            ],
        ],
        [
            'slug' => 'carpenter-service',
            'name' => 'Carpenter Service',
            'match' => ['Carpenter', 'Carpenter Services'],
            'page_title' => 'Carpenter Services',
            'description' => 'Professional carpenter services for doors, cupboards, furniture fittings, repairs and home installations.',
            'tagline' => 'Furniture & woodwork',
            'icon' => 'fa-solid fa-hammer',
            'label' => 'HOME REPAIR',
            'highlights' => ['Furniture Repair', 'Door Repair', 'Installation'],
            'image' => 'images/car-panter-service.png',
            'cover_image' => 'images/carpenter-service.png',
            'sort' => 9,
            'services' => [
                [
                    'slug' => 'carpenter-door-accessory',
                    'name' => 'Door Accessory Installation',
                    'match' => [],
                    'tag' => 'DOOR SERVICE',
                    'description' => 'Installation of essential door accessories including hinges, chains, latches and closers.',
                    'highlights' => ['Accessory Installation', 'Door Alignment', 'Functionality Testing'],
                    'price' => 399,
                    'image' => 'images/door-accessory-installation.png',
                    'sort' => 1,
                ],
                [
                    'slug' => 'carpenter-door-lock',
                    'name' => 'Door Lock Replacement',
                    'match' => [],
                    'tag' => 'LOCK SERVICE',
                    'description' => 'Remove the old door lock and professionally install a new lock with proper alignment.',
                    'highlights' => ['Old Lock Removal', 'New Lock Installation', 'Operational Testing'],
                    'price' => 499,
                    'image' => 'images/door-lock-replacement.png',
                    'sort' => 2,
                ],
                [
                    'slug' => 'carpenter-door-installation',
                    'name' => 'Door Installation',
                    'match' => [],
                    'tag' => 'INSTALLATION',
                    'description' => 'Professional installation of new doors with secure fitting, hinge installation and alignment.',
                    'highlights' => ['Door Fitting', 'Hinge Installation', 'Door Alignment'],
                    'price' => 1999,
                    'image' => 'images/door-installation-service.png',
                    'sort' => 3,
                ],
                [
                    'slug' => 'carpenter-mesh-grill',
                    'name' => 'Mesh Grill Door Replacement',
                    'match' => [],
                    'tag' => 'DOOR REPLACEMENT',
                    'description' => 'Remove the old mesh grill door and install a replacement with proper alignment and fitting.',
                    'highlights' => ['Old Door Removal', 'Mesh Grill Installation', 'Alignment Adjustment'],
                    'price' => 1499,
                    'image' => 'images/mesh-grill-door-replacement.png',
                    'sort' => 4,
                ],
                [
                    'slug' => 'carpenter-curtain-rod',
                    'name' => 'Curtain Rod Installation',
                    'match' => [],
                    'tag' => 'HOME FITTING',
                    'description' => 'Professional measuring, bracket fitting and installation of curtain rods with proper alignment.',
                    'highlights' => ['Position Measurement', 'Bracket Installation', 'Rod Alignment'],
                    'price' => 299,
                    'image' => 'images/curtain-rod-installation.png',
                    'sort' => 5,
                ],
                [
                    'slug' => 'carpenter-bed-support',
                    'name' => 'Bed Support Repair',
                    'match' => [],
                    'tag' => 'FURNITURE REPAIR',
                    'description' => 'Inspection and repair of broken or weak bed support slats and damaged support structures.',
                    'highlights' => ['Support Inspection', 'Support Reinforcement', 'Damaged Support Repair'],
                    'price' => 799,
                    'image' => 'images/bed-support-repair.png',
                    'sort' => 6,
                ],
                [
                    'slug' => 'carpenter-cupboard-hinge',
                    'name' => 'Cupboard Hinge Installation',
                    'match' => [],
                    'tag' => 'CUPBOARD SERVICE',
                    'description' => 'Installation of new cupboard hinges with alignment and adjustment for smooth door movement.',
                    'highlights' => ['New Hinge Installation', 'Cupboard Door Alignment', 'Hinge Screw Tightening'],
                    'price' => 199,
                    'image' => 'images/cupboard-hinge-installation.png',
                    'sort' => 7,
                ],
            ],
        ],
    ],
    'banners' => [
        [
            'key' => 'homepage-hero',
            'title' => 'Zen Care Professional Service',
            'placement' => 'Homepage Hero',
            'image' => 'images/ac-installation-service.png',
            'link' => 'services.php',
            'sort' => 1,
        ],
    ],
];
